# Generated by Django 3.1.3 on 2020-11-05 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mangaka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_muerte', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
            options={
                'ordering': ['apellido', 'primer_nombre'],
            },
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='manga',
            name='Mangaka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.mangaka'),
        ),
    ]
