# Generated by Django 3.1.3 on 2020-11-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20201104_2355'),
        ('catalogo', '0002_auto_20201016_0300'),
    ]

    operations = [
    ]
